version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "$HOME/docker_learning/dockerWithPytorch/notebook_host:/notebooks"
    deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: "jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks"
